# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: azure vnet list
  inputs:
    azureSubscription: 'aks_vnet_details'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: '$(Build.SourcesDirectory)/vnet_list.sh'
    arguments: '-rg=aks'
    useGlobalConfig: true
    workingDirectory: '$(Build.SourcesDirectory)'
    failOnStandardError: true
  continueOnError: false
  enabled: true
  