# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: azure vnet list
  inputs:
    azureSubscription: 'aks_vnet_details'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: '$(Build.SourcesDirectory)/vnet_list.sh'
    arguments: '-rg=aks'
    useGlobalConfig: true
    workingDirectory: '$(Build.SourcesDirectory)'
    failOnStandardError: true
  continueOnError: false
  enabled: true

- task: CopyFiles@2
  displayName: copy files to artifact stagging directory
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true
    preserveTimestamp: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'vnet_config_data'
    publishLocation: 'Container'
  condition: succeeded()